[main]
image=fedora-toolbox:43
home=~/dbox/main/
#nvidia=true
root=false

#additional_flags="--gpus all --group-add keep-groups"

#enable rpmfusion
pre_init_hooks="dnf install -y install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm;"
#enable copr repo for lf 
pre_init_hooks=cd /etc/yum.repos.d/ && wget https://copr.fedorainfracloud.org/coprs/pennbauman/ports/repo/fedora-"$(rpm -E %fedora)"/pennbauman-ports-fedora-"$(rpm -E %fedora)".repo;

#cli programs
additional_packages="zsh jmtpfs lf neovim tldr htop nvtop btop"

#nvchad deps
additional_packages="ripgrep npm shellcheck"

#archive handling
additional_packages="7zip unrar"

#background stuff needed for scripts
additional_packages="ImageMagick bat ffmpegthumbnailer file xpdf trash-cli jq"

#GUI programs  
additional_packages="zathura zathura-cb zathura-djvu zathura-pdf-mupdf"

#Gaming
additional_packages="gamescope mangohud vulkan-tools"

#media
additional_packages="mpv ncmpcpp yt-dlp yt-dlp-zsh-completion chafa imv mpd"

#misc libs
additional_packages="libicu libatomic gstreamer1-vaapi GConf2 zenity foot-terminfo iputils dbus-daemon fuse fuse-libs"
#init_hooks="mkdir /run/dbus;"

#development stuff
additional_packages="git python3-pip g++"
init_hooks="dnf -y group install development-tools;"

#fonts
additional_packages="google-noto-fonts-all"

#install usoc mpv config
init_hooks=curl -fsSL https://raw.githubusercontent.com/tomasklaen/uosc/HEAD/installers/unix.sh | bash;

#install fastanime
additional_packages="uv"
init_hooks=uv tool install "fastanime[mpv]";

#change shell
pre_init_hooks="export SHELL=/usr/bin/zsh;"

#fix xwayland issues in container
init_hooks="install -o 1000 -g 1000 -d /tmp/.X11-unix-new; mount --bind /tmp/.X11-unix-new /tmp/.X11-unix;"

# starts dbus in container
# TODO causes errors when run multiple times
#init_hooks="! [ -d "/run/dbus" ] && mkdir /run/dbus; dbus-daemon --system;"

# sets up xdg-open in container to open host executables, mainly for browser
init_hooks="ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;"


[ai-cuda]
image=ubuntu:24.04
home=~/dbox/ai/
nvidia=true
root=false

additional_packages="git git-lfs neovim build-essential cmake npm"

# had to remove fuse3 due to errors
additional_packages="unzip zip p7zip-full zsh fuse imagemagick" 

additional_packages="python3 python3-pip python3-venv"

#additional_packages="rust cargo openssl-devel"
additional_packages="rust-all cargo"

#renamed to gperftools in later debian versions
additional_packages="google-perftools" 

#install missing graphics libraries for ComfyUI nodes
additional_packages="libopengl0 libglfw3 libglfw3-dev libffmpeg-nvenc-dev ffmpeg"

#need to install this to get newer versions of node
init_hooks=curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash;

#install espeak-ng for Kokoro-FastAPI
#sudo apt install -y espeak-ng espeak-ng-data
#sudo ln -s /usr/lib/x86_64-linux-gnu/espeak-ng-data /usr/share/espeak-ng-data

# for https://github.com/mirabarukaso/character_select_stand_alone_app
additional_packages="libnspr4  libnss3"

#change shell
pre_init_hooks="export SHELL=/usr/bin/zsh;"

# install git-xet, and hf cli
init_hooks="curl -sSfL https://hf.co/git-xet/install.sh | sh"
init_hooks="curl -LsSf https://hf.co/cli/install.sh | bash"
