#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the ""$MOD"" modifier is also known as Logo, GUI, Windows, Mod4, etc.

MOD="Alt"


# "$MOD"+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal "$MOD"+Shift Return spawn foot

# "$MOD"+Q to close the focused view
riverctl map normal "$MOD" Q close

# "$MOD"+Shift+E to exit river
riverctl map normal "$MOD"+Shift E exit

# "$MOD"+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal "$MOD" J focus-view next
riverctl map normal "$MOD" K focus-view previous

# "$MOD"+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal "$MOD"+Shift J swap next
riverctl map normal "$MOD"+Shift K swap previous

# "$MOD"+Period and Super+Comma to focus the next/previous output
riverctl map normal "$MOD" Period focus-output next
riverctl map normal "$MOD" Comma focus-output previous

# "$MOD"+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal "$MOD"+Shift Period send-to-output next
riverctl map normal "$MOD"+Shift Comma send-to-output previous

# "$MOD"+Return to bump the focused view to the top of the layout stack
riverctl map normal "$MOD" Return zoom

# "$MOD"+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal "$MOD" H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal "$MOD" L send-layout-cmd rivertile "main-ratio +0.05"

# "$MOD"+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal "$MOD"+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal "$MOD"+Shift L send-layout-cmd rivertile "main-count -1"

# "$MOD"+Alt+{H,J,K,L} to move views
#riverctl map normal "$MOD"+Alt H move left 100
#riverctl map normal "$MOD"+Alt J move down 100
#riverctl map normal "$MOD"+Alt K move up 100
#riverctl map normal "$MOD"+Alt L move right 100

# "$MOD"+Alt+Control+{H,J,K,L} to snap views to screen edges
#riverctl map normal "$MOD"+Alt+Control H snap left
#riverctl map normal "$MOD"+Alt+Control J snap down
#riverctl map normal "$MOD"+Alt+Control K snap up
#riverctl map normal "$MOD"+Alt+Control L snap right

# "$MOD"+Alt+Shif+{H,J,K,L} to resize views
#riverctl map normal "$MOD"+Alt+Shift H resize horizontal -100
#riverctl map normal "$MOD"+Alt+Shift J resize vertical 100
#riverctl map normal "$MOD"+Alt+Shift K resize vertical -100
#riverctl map normal "$MOD"+Alt+Shift L resize horizontal 100

# "$MOD" + Left Mouse Button to move views
riverctl map-pointer normal "$MOD" BTN_LEFT move-view

# "$MOD" + Right Mouse Button to resize views
riverctl map-pointer normal "$MOD" BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # "$MOD"+[1-9] to focus tag [0-8]
    riverctl map normal "$MOD" $i set-focused-tags $tags

    # "$MOD"+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal "$MOD"+Shift $i set-view-tags $tags

    # "$MOD"+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal "$MOD"+Control $i toggle-focused-tags $tags

    # "$MOD"+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal "$MOD"+Shift+Control $i toggle-view-tags $tags
done

# "$MOD"+0 to focus all tags
# "$MOD"+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal "$MOD" 0 set-focused-tags $all_tags
riverctl map normal "$MOD"+Shift 0 set-view-tags $all_tags

# "$MOD"+Space to toggle float
riverctl map normal "$MOD" Space toggle-float

# "$MOD"+F to toggle fullscreen
riverctl map normal "$MOD" F toggle-fullscreen

# "$MOD"+{Up,Right,Down,Left} to change layout orientation
riverctl map normal "$MOD" Up    send-layout-cmd rivertile "main-location top"
riverctl map normal "$MOD" Right send-layout-cmd rivertile "main-location right"
riverctl map normal "$MOD" Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal "$MOD" Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# "$MOD"+F11 to enter passthrough mode
riverctl map normal "$MOD" F11 enter-mode passthrough

# "$MOD"+F11 to return to normal mode
riverctl map passthrough "$MOD" F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'vol.sh -i 0.02'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'vol.sh -d 0.02'
    riverctl map $mode None XF86AudioMute         spawn 'vol.sh --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

#custom config
riverctl set-cursor-warp on-output-change 
#riverctl input INPUT_POINTER_NAME accel-profile flat
riverctl map normal "$MOD" P spawn bemenu-run 
riverctl focus-follows-cursor normal
riverctl spawn ~/.init.sh

#startup programs
#riverctl spawn waybar
riverctl spawn "dms run"
riverctl spawn "wl-paste --watch cliphist store"
riverctl spawn "~/.local/scripts/gammastep-init.sh"
riverctl spawn "udiskie"
riverctl spawn "kanshi"

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 6 -outer-padding 6
