rootcolor=0x282c34ff #base00
bordercolor=0x353b45ff #base01
focuscolor=#0xabb2bfff  #base05
maximizescreencolor=0x61afefff #base0D
urgentcolor=0xe06c75ff #base08
scratchpadcolor=0xd19a66ff #base09 (just picked something)
globalcolor=0xc678ddff     #base0E (just picked something)
overlaycolor=0x98c379ff    #base0B (just picked something)
